In [2]:
import os
import re
import pandas as pd
import matplotlib.pyplot as plt
from utils_analysis import *
import numpy as np
import seaborn as sb
from collections import Counter

In [4]:
prefix = "/infres/ir800/rapaport/altered-history/results/2021/new"
class_files = os.listdir(prefix)
df = pd.DataFrame()
for file in class_files:
    file_path = os.path.join(prefix, file)
    #print("parsing file: ", file_path)
    if os.path.isfile(file_path) and file_path != "/infres/ir800/rapaport/phd-solal/dev/rust/missing_commits/results/2021/new/checkpoints":
        df = pd.concat([df, pd.read_csv(prefix + "/" + file, delimiter=";")])
df

,21:25:25 [INFO] couldn't open checkpoints file,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,09:20:32 [INFO] Not calculating Origin: deb://Debian/packages/accerciser,deb://Debian/packages/apt-forktracer
0,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://github.com/shibing624/pycorrector
2176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://gitlab.com/hesafredrika/server.git
2177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://gitlab.com/johnivore/gitstat.git
2178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://github.com/tqdm/tqdm
2179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://gitlab.com/elixire/elixire.git

In [5]:
prefix = "/infres/ir800/rapaport/altered-history/results/2021/new/focus/classes"
class_files = os.listdir(prefix)
df_root = pd.DataFrame()
for file in class_files: 
    #print("parsing file ", file)
    df_root = pd.concat([df, pd.read_csv(prefix + "/" + file, delimiter=";")])
df_root

,21:25:25 [INFO] couldn't open checkpoints file,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,09:20:32 [INFO] Not calculating Origin: deb://Debian/packages/accerciser,deb://Debian/packages/apt-forktracer,first_difference,main_category,sub_categories
0,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21:25:25 [INFO] Checking Origin: deb://Debian/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5,NaN,https://github.com/python/cpython,swh:1:snp:f02a9539e85500589cc500fad461817b4e2a...,refs/heads/master,swh:1:rev:b5e5004ae8f54d7d5ddfa0688fc8385cafde...,swh:1:snp:ed15097246cbe4bf33b2e4f822fc453cd97f...,NaN,NaN,"Some(""swh:1:rev:3310257195daa702bc91fb90e78ac9...",META,"{Date, Message, CommitterDate}"
6,NaN,https://gitlab.com/elixire/elixire.git,swh:1:snp:7ccd57a04711637add6b6f34fd38c02596f2...,refs/heads/master,swh:1:rev:94effdb79f9182c63887a6961436317b484b...,swh:1:snp:e0f20dc38bc0ddf4a161f762de419baf5fe9...,NaN,NaN,None,DIR,{ContentRemoved}
7,NaN,https://github.com/Tribler/tribler,swh:1:snp:4d2244ab144b195574d55581318ad66ab4fe...,refs/heads/devel,swh:1:rev:ec8b94ae8c687fbd82a9338fe0ee6041013d...,swh:1:snp:88d4cbf8c3f6816cba33010d0fdfc6fdf774...,NaN,NaN,None,DIR,{ContentDiluted}
8,NaN,https://github.com/stanfordnlp/stanza,swh:1:snp:2b923568deecc3630f5031c9e5c2f6660445...,refs/heads/master,swh:1:rev:fcc31d77e41e078e812fa03cf2097ea149aa...,swh:1:snp:f49d8d7d7ef289be788b0683779a9ac58711...,NaN,NaN,None,DIR,"{ContentRemoved, ContentModified}"
9,NaN,https://github.com/MycroftAI/mycroft-core,swh:1:snp:a02b17e52df3de64e5876303abffd656e626...,refs/heads/dev,swh:1:rev:d5c447c07bec51be9ef04f3a3f657b4b49cc...,swh:1:snp:a4216e7d165e1a6b65946196202b44becca4...,NaN,NaN,"Some(""swh:1:rev:d5c447c07bec51be9ef04f3a3f657b...",DIR,{DifferentBranchName}

In [19]:
pattern = r"^refs/heads/(main|master|dev|devel|develop|development)$"
#df = df.loc[df['branch_name'].apply(lambda x: re.search(pattern, x) is not None)]
#df_root = df_root.loc[df_root['branch_name'].apply(lambda x: re.search(pattern, x) is not None)]
print(len(df['origin'].drop_duplicates()))
print(len(df_root['origin'].drop_duplicates()))

34
35

In [9]:
origin_counts = df['origin'].value_counts().to_dict()
origin_counts_root = df_root['origin'].value_counts().to_dict()

In [10]:
merged_counts = {key: (origin_counts.get(key, 0), origin_counts_root.get(key, 0)) for key in set(origin_counts) | set(origin_counts_root)}

In [ ]:
import json 
with open("snowball.json", "w") as f:
    f.write(json.dumps(merged_counts, indent=1))

In [12]:
len(origin_counts)

30

In [ ]:
filtered_counts = {key: value for key, value in merged_counts.items() if value[1] > 0 and value[0]!=value[1]}
sorted_filtered_counts = dict(sorted(filtered_counts.items(), key=lambda item: item[1][0] - item[1][1], reverse=True))
sorted_filtered_counts

In [ ]:
sum_value_1 = sum(value[1] for value in merged_counts.values())
sum_value_1